# Generated by Django 3.1.1 on 2020-11-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('AC', '사용하기'), ('UN', '현재 장소에서 사용이 불가능한 아이템입니다.'), ('AU', '이미 사용한 아이템입니다.')], default='AC', max_length=50),
            preserve_default=False,
        ),
    ]
