# Generated by Django 3.1.1 on 2020-11-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='del_assistance',
            field=models.BooleanField(default=False),
        ),
    ]
