# Generated by Django 3.1.1 on 2020-11-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_del_assistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='open_hydrant',
            field=models.BooleanField(default=False),
        ),
    ]
